# Generated by Django 6.0.5 on 2026-05-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_approval_status_user_last_active_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='disposalguideline',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ewastecategoryconfig',
            name='category',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
