# Generated by Django 6.0.3 on 2026-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='user_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='user_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='user_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
