# Generated by Django 6.0.3 on 2026-05-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_collectionrequest_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
