# Generated by Django 6.0.3 on 2026-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_collectionrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('picked_up', 'Picked Up'), ('completed', 'Completed'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
