# Generated by Django 6.0.3 on 2026-05-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_collectionrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='api.ewastecategoryconfig', to_field='category'),
        ),
    ]
