# Generated by Django 6.0.3 on 2026-05-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_collectionrequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
