# Generated by Django 6.0.5 on 2026-05-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_collectionrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
